import '../models/user/User.dart';

///    required this.id,
//     this.company,
//     this.firstName,
//     this.lastName,
//     this.email,
//     this.street,
//     this.birthdate,
//     this.holiday,
//     this.yearsOfEmployment,
//     this.age,
//     this.employment,
//     this.kids,
//     this.student,
//     this.roles,
//     this.calendars,
//     this.deputy,
//     this.district,
//     this.rank,
//     this.priority,

User user1 = User(
    id: '1',
    company: 'Braso AG',
    firstName: 'Max',
    lastName: 'Muster',
    email: 'max@muster.ch',
    street: 'Musterstrasse 1',
    birthdate: '01 / 01 / 2000',
    holiday: 25,
    yearsOfEmployment: '01 / 01 / 2000',
    age: 24,
    employment: 100,
    kids: false,
    student: true,
    roles: null,
    calendars: null,
    deputy: null,
    district: null,
    rank: null,
    priority: null);
